CREATE DATABASE poma;
USE poma;
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
-- Wszystko do odkomentowania - zakomentowane do testów
-- tam gdzie jest jakies odwołanie do pliku audio bedzie te
/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/
--
-- Struktura tabeli dla tabeli `mvc_konkurs_batalia`
--

CREATE TABLE IF NOT EXISTS `mvc_konkurs_batalia` (
  `runda` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `druzyna_id` int(11) NOT NULL,
  `kategoria` varchar(255) NOT NULL,
  `poziom` int(11) NOT NULL,
  `img_odpowiedzi` varchar(255) NOT NULL,
  `img_pytania` varchar(255) NOT NULL,
  `event` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `mvc_konkurs_pytania`
--

CREATE TABLE IF NOT EXISTS `mvc_konkurs_pytania` (
  `id` int(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `kategoria` varchar(255) NOT NULL,
  `poziom` int(11) NOT NULL,
  `img_pytania` varchar(255) NOT NULL,
  `img_odpowiedzi` varchar(255) NOT NULL,
  `uzyte` boolean,
  `media` varchar(255) NOT NULL,
  `media_typ` enum('','audio','wideo') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Zrzut danych tabeli `mvc_konkurs_pytania`
--

INSERT INTO `mvc_konkurs_pytania` (`id`, `kategoria`, `poziom`, `img_pytania`, 
`img_odpowiedzi`, `uzyte`, `media`, `media_typ`) VALUES
-- (default, 'bonus', 1, 'baza/bonus/1/b1.jpg', 'baza/bonus/1/bo1.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b10.jpg', 'baza/bonus/1/bo10.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b11.jpg', 'baza/bonus/1/bo11.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b12.jpg', 'baza/bonus/1/bo12.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b13.jpg', 'baza/bonus/1/bo13.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b14.jpg', 'baza/bonus/1/bo14.jpg', 0, 'baza/audio/b14.mp3', 'audio'),
-- (default, 'bonus', 1, 'baza/bonus/1/b15.jpg', 'baza/bonus/1/bo15.jpg', 0, 'baza/audio/b15.mp3', 'audio'),
-- (default, 'bonus', 1, 'baza/bonus/1/b16.jpg', 'baza/bonus/1/bo16.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b17.jpg', 'baza/bonus/1/bo17.jpg', 0, 'baza/wideo/b17.mp4', 'wideo'),
-- (default, 'bonus', 1, 'baza/bonus/1/b18.jpg', 'baza/bonus/1/bo18.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b2.jpg', 'baza/bonus/1/bo2.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b3.jpg', 'baza/bonus/1/bo3.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b4.jpg', 'baza/bonus/1/bo4.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b5.jpg', 'baza/bonus/1/bo5.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b6.jpg', 'baza/bonus/1/bo6.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b7.jpg', 'baza/bonus/1/bo7.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b8.jpg', 'baza/bonus/1/bo8.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b9.jpg', 'baza/bonus/1/bo9.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b19.jpg', 'baza/bonus/1/bo19.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b20.jpg', 'baza/bonus/1/bo20.jpg', 0, '', '' ),
-- (default, 'bonus', 1, 'baza/bonus/1/b21.jpg', 'baza/bonus/1/bo21.jpg', 0,'baza/wideo/b21.mp4', 'wideo' ),
-- (default, 'bonus', 1, 'baza/bonus/1/b22.jpg', 'baza/bonus/1/bo22.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b23.jpg', 'baza/bonus/1/bo23.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b24.jpg', 'baza/bonus/1/bo24.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b25.jpg', 'baza/bonus/1/bo25.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b26.jpg', 'baza/bonus/1/bo26.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b27.jpg', 'baza/bonus/1/bo27.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b28.jpg', 'baza/bonus/1/bo28.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b29.jpg', 'baza/bonus/1/bo29.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b30.jpg', 'baza/bonus/1/bo30.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b31.jpg', 'baza/bonus/1/bo31.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b32.jpg', 'baza/bonus/1/bo32.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b33.jpg', 'baza/bonus/1/bo33.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b34.jpg', 'baza/bonus/1/bo34.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b35.jpg', 'baza/bonus/1/bo35.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b36.jpg', 'baza/bonus/1/bo36.jpg', 0, '', ''),
-- (default, 'bonus', 1, 'baza/bonus/1/b37.jpg', 'baza/bonus/1/bo37.jpg', 0, '', ''),

-- (default, 'chemia', 1, 'baza/chemia/1/c10.jpg', 'baza/chemia/1/co10.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c11.jpg', 'baza/chemia/1/co11.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c12.jpg', 'baza/chemia/1/co12.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c13.jpg', 'baza/chemia/1/co13.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c14.jpg', 'baza/chemia/1/co14.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c15.jpg', 'baza/chemia/1/co15.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c16.jpg', 'baza/chemia/1/co16.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c17.jpg', 'baza/chemia/1/co17.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c18.jpg', 'baza/chemia/1/co18.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c19.jpg', 'baza/chemia/1/co19.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c2.jpg', 'baza/chemia/1/co2.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c20.jpg', 'baza/chemia/1/co20.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c21.jpg', 'baza/chemia/1/co21.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c22.jpg', 'baza/chemia/1/co22.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c23.jpg', 'baza/chemia/1/co23.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c24.jpg', 'baza/chemia/1/co24.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c25.jpg', 'baza/chemia/1/co25.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c26.jpg', 'baza/chemia/1/co26.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c27.jpg', 'baza/chemia/1/co27.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c28.jpg', 'baza/chemia/1/co28.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c29.jpg', 'baza/chemia/1/co29.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c3.jpg', 'baza/chemia/1/co3.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c30.jpg', 'baza/chemia/1/co30.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c31.jpg', 'baza/chemia/1/co31.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c32.jpg', 'baza/chemia/1/co32.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c33.jpg', 'baza/chemia/1/co33.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c34.jpg', 'baza/chemia/1/co34.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c35.jpg', 'baza/chemia/1/co35.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c36.jpg', 'baza/chemia/1/co36.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c37.jpg', 'baza/chemia/1/co37.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c38.jpg', 'baza/chemia/1/co38.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c39.jpg', 'baza/chemia/1/co39.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c4.jpg', 'baza/chemia/1/co4.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c40.jpg', 'baza/chemia/1/co40.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c41.jpg', 'baza/chemia/1/co41.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c42.jpg', 'baza/chemia/1/co42.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c43.jpg', 'baza/chemia/1/co43.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c44.jpg', 'baza/chemia/1/co44.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c45.jpg', 'baza/chemia/1/co45.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c46.jpg', 'baza/chemia/1/co46.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c47.jpg', 'baza/chemia/1/co47.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c48.jpg', 'baza/chemia/1/co48.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c49.jpg', 'baza/chemia/1/co49.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c5.jpg', 'baza/chemia/1/co5.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c50.jpg', 'baza/chemia/1/co50.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c51.jpg', 'baza/chemia/1/co51.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c52.jpg', 'baza/chemia/1/co52.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c53.jpg', 'baza/chemia/1/co53.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c54.jpg', 'baza/chemia/1/co54.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c55.jpg', 'baza/chemia/1/co55.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c56.jpg', 'baza/chemia/1/co56.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c57.jpg', 'baza/chemia/1/co57.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c58.jpg', 'baza/chemia/1/co58.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c1.jpg', 'baza/chemia/1/co1.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c6.jpg', 'baza/chemia/1/co6.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c7.jpg', 'baza/chemia/1/co7.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c8.jpg', 'baza/chemia/1/co8.jpg', 0, '', ''),
-- (default, 'chemia', 1, 'baza/chemia/1/c9.jpg', 'baza/chemia/1/co9.jpg', 0, '', ''),

(default, 'chemia', 2, 'baza_pytania/chemia/poziom_2/c1.jpg', 'baza_pytania/chemia/poziom_2/co1.jpg', 'flase', '', ''),
(default, 'chemia', 2, 'baza_pytania/chemia/poziom_2/c2.jpg', 'baza_pytania/chemia/poziom_2/co2.jpg', 'false', '', ''),
(default, 'chemia', 2, 'baza_pytania/chemia/poziom_2/c3.jpg', 'baza_pytania/chemia/poziom_2/co3.jpg', 'fasle', '', ''),
(default, 'chemia', 2, 'baza_pytania/chemia/poziom_2/c4.jpg', 'baza_pytania/chemia/poziom_2/co4.jpg', 'false', '', ''),
(default, 'chemia', 2, 'baza_pytania/chemia/poziom_2/c5.jpg', 'baza_pytania/chemia/poziom_2/co5.jpg', 'false', '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c6.jpg', 'baza/chemia/2/co6.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c7.jpg', 'baza/chemia/2/co7.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c8.jpg', 'baza/chemia/2/co8.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c9.jpg', 'baza/chemia/2/co9.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c10.jpg', 'baza/chemia/2/co10.jpg', 0, '', ''),

-- (default, 'chemia', 2, 'baza/chemia/2/c11.jpg', 'baza/chemia/2/co11.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c12.jpg', 'baza/chemia/2/co12.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c13.jpg', 'baza/chemia/2/co13.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c14.jpg', 'baza/chemia/2/co14.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c15.jpg', 'baza/chemia/2/co15.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c16.jpg', 'baza/chemia/2/co16.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c17.jpg', 'baza/chemia/2/co17.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c18.jpg', 'baza/chemia/2/co18.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c19.jpg', 'baza/chemia/2/co19.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c20.jpg', 'baza/chemia/2/co20.jpg', 0, '', ''),

-- (default, 'chemia', 2, 'baza/chemia/2/c21.jpg', 'baza/chemia/2/co21.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c22.jpg', 'baza/chemia/2/co22.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c23.jpg', 'baza/chemia/2/co23.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c24.jpg', 'baza/chemia/2/co24.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c25.jpg', 'baza/chemia/2/co25.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c26.jpg', 'baza/chemia/2/co26.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c27.jpg', 'baza/chemia/2/co27.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c28.jpg', 'baza/chemia/2/co28.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c29.jpg', 'baza/chemia/2/co29.jpg', 0, '', ''),

-- (default, 'chemia', 2, 'baza/chemia/2/c30.jpg', 'baza/chemia/2/co30.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c31.jpg', 'baza/chemia/2/co31.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c32.jpg', 'baza/chemia/2/co32.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c33.jpg', 'baza/chemia/2/co33.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c34.jpg', 'baza/chemia/2/co34.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c35.jpg', 'baza/chemia/2/co35.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c36.jpg', 'baza/chemia/2/co36.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c37.jpg', 'baza/chemia/2/co37.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c38.jpg', 'baza/chemia/2/co38.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c39.jpg', 'baza/chemia/2/co39.jpg', 0, '', ''),

-- (default, 'chemia', 2, 'baza/chemia/2/c40.jpg', 'baza/chemia/2/co40.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c41.jpg', 'baza/chemia/2/co41.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c42.jpg', 'baza/chemia/2/co42.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c43.jpg', 'baza/chemia/2/co43.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c44.jpg', 'baza/chemia/2/co44.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c45.jpg', 'baza/chemia/2/co45.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c46.jpg', 'baza/chemia/2/co46.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c47.jpg', 'baza/chemia/2/co47.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c48.jpg', 'baza/chemia/2/co48.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c49.jpg', 'baza/chemia/2/co49.jpg', 0, '', ''),

-- (default, 'chemia', 2, 'baza/chemia/2/c50.jpg', 'baza/chemia/2/co50.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c51.jpg', 'baza/chemia/2/co51.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c52.jpg', 'baza/chemia/2/co52.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c53.jpg', 'baza/chemia/2/co53.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c54.jpg', 'baza/chemia/2/co54.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c55.jpg', 'baza/chemia/2/co55.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c56.jpg', 'baza/chemia/2/co56.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c57.jpg', 'baza/chemia/2/co57.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c58.jpg', 'baza/chemia/2/co58.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c59.jpg', 'baza/chemia/2/co59.jpg', 0, '', ''),


-- (default, 'chemia', 2, 'baza/chemia/2/c60.jpg', 'baza/chemia/2/co60.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c61.jpg', 'baza/chemia/2/co61.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c62.jpg', 'baza/chemia/2/co62.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c63.jpg', 'baza/chemia/2/co63.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c64.jpg', 'baza/chemia/2/co64.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c65.jpg', 'baza/chemia/2/co65.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c66.jpg', 'baza/chemia/2/co66.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c67.jpg', 'baza/chemia/2/co67.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c68.jpg', 'baza/chemia/2/co68.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c69.jpg', 'baza/chemia/2/co69.jpg', 0, '', ''),

-- (default, 'chemia', 2, 'baza/chemia/2/c70.jpg', 'baza/chemia/2/co70.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c71.jpg', 'baza/chemia/2/co71.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c72.jpg', 'baza/chemia/2/co72.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c73.jpg', 'baza/chemia/2/co73.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c74.jpg', 'baza/chemia/2/co74.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c75.jpg', 'baza/chemia/2/co75.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c76.jpg', 'baza/chemia/2/co76.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c77.jpg', 'baza/chemia/2/co77.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c78.jpg', 'baza/chemia/2/co78.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c79.jpg', 'baza/chemia/2/co79.jpg', 0, '', ''),
-- (default, 'chemia', 2, 'baza/chemia/2/c80.jpg', 'baza/chemia/2/co80.jpg', 0, '', ''),

-- (default, 'fizyka', 1, 'baza/fizyka/1/f1.jpg', 'baza/fizyka/1/fo1.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f10.jpg', 'baza/fizyka/1/fo10.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f11.jpg', 'baza/fizyka/1/fo11.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f12.jpg', 'baza/fizyka/1/fo12.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f13.jpg', 'baza/fizyka/1/fo13.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f14.jpg', 'baza/fizyka/1/fo14.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f15.jpg', 'baza/fizyka/1/fo15.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f16.jpg', 'baza/fizyka/1/fo16.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f17.jpg', 'baza/fizyka/1/fo17.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f18.jpg', 'baza/fizyka/1/fo18.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f19.jpg', 'baza/fizyka/1/fo19.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f2.jpg', 'baza/fizyka/1/fo2.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f20.jpg', 'baza/fizyka/1/fo20.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f21.jpg', 'baza/fizyka/1/fo21.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f22.jpg', 'baza/fizyka/1/fo22.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f23.jpg', 'baza/fizyka/1/fo23.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f24.jpg', 'baza/fizyka/1/fo24.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f25.jpg', 'baza/fizyka/1/fo25.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f26.jpg', 'baza/fizyka/1/fo26.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f27.jpg', 'baza/fizyka/1/fo27.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f28.jpg', 'baza/fizyka/1/fo28.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f29.jpg', 'baza/fizyka/1/fo29.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f3.jpg', 'baza/fizyka/1/fo3.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f30.jpg', 'baza/fizyka/1/fo30.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f31.jpg', 'baza/fizyka/1/fo31.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f32.jpg', 'baza/fizyka/1/fo32.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f33.jpg', 'baza/fizyka/1/fo33.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f34.jpg', 'baza/fizyka/1/fo34.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f35.jpg', 'baza/fizyka/1/fo35.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f36.jpg', 'baza/fizyka/1/fo36.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f37.jpg', 'baza/fizyka/1/fo37.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f38.jpg', 'baza/fizyka/1/fo38.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f39.jpg', 'baza/fizyka/1/fo39.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f4.jpg', 'baza/fizyka/1/fo4.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f40.jpg', 'baza/fizyka/1/fo40.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f41.jpg', 'baza/fizyka/1/fo41.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f42.jpg', 'baza/fizyka/1/fo42.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f43.jpg', 'baza/fizyka/1/fo43.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f44.jpg', 'baza/fizyka/1/fo44.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f45.jpg', 'baza/fizyka/1/fo45.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f46.jpg', 'baza/fizyka/1/fo46.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f47.jpg', 'baza/fizyka/1/fo47.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f48.jpg', 'baza/fizyka/1/fo48.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f49.jpg', 'baza/fizyka/1/fo49.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f5.jpg', 'baza/fizyka/1/fo5.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f50.jpg', 'baza/fizyka/1/fo50.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f51.jpg', 'baza/fizyka/1/fo51.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f52.jpg', 'baza/fizyka/1/fo52.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f53.jpg', 'baza/fizyka/1/fo53.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f54.jpg', 'baza/fizyka/1/fo54.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f55.jpg', 'baza/fizyka/1/fo55.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f56.jpg', 'baza/fizyka/1/fo56.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f57.jpg', 'baza/fizyka/1/fo57.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f58.jpg', 'baza/fizyka/1/fo58.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f59.jpg', 'baza/fizyka/1/fo59.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f6.jpg', 'baza/fizyka/1/fo6.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f60.jpg', 'baza/fizyka/1/fo60.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f61.jpg', 'baza/fizyka/1/fo61.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f62.jpg', 'baza/fizyka/1/fo62.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f63.jpg', 'baza/fizyka/1/fo63.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f64.jpg', 'baza/fizyka/1/fo64.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f65.jpg', 'baza/fizyka/1/fo65.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f66.jpg', 'baza/fizyka/1/fo66.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f67.jpg', 'baza/fizyka/1/fo67.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f68.jpg', 'baza/fizyka/1/fo68.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f69.jpg', 'baza/fizyka/1/fo69.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f7.jpg', 'baza/fizyka/1/fo7.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f8.jpg', 'baza/fizyka/1/fo8.jpg', 0, '', ''),
-- (default, 'fizyka', 1, 'baza/fizyka/1/f9.jpg', 'baza/fizyka/1/fo9.jpg', 0, '', ''),


-- (default, 'fizyka', 2, 'baza/fizyka/2/f1.jpg', 'baza/fizyka/2/fo1.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f2.jpg', 'baza/fizyka/2/fo2.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f3.jpg', 'baza/fizyka/2/fo3.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f4.jpg', 'baza/fizyka/2/fo4.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f5.jpg', 'baza/fizyka/2/fo5.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f6.jpg', 'baza/fizyka/2/fo6.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f7.jpg', 'baza/fizyka/2/fo7.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f8.jpg', 'baza/fizyka/2/fo8.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f9.jpg', 'baza/fizyka/2/fo9.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f10.jpg', 'baza/fizyka/2/fo10.jpg', 0, '', ''),

-- (default, 'fizyka', 2, 'baza/fizyka/2/f11.jpg', 'baza/fizyka/2/fo11.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f12.jpg', 'baza/fizyka/2/fo12.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f13.jpg', 'baza/fizyka/2/fo13.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f14.jpg', 'baza/fizyka/2/fo14.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f15.jpg', 'baza/fizyka/2/fo15.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f16.jpg', 'baza/fizyka/2/fo16.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f17.jpg', 'baza/fizyka/2/fo17.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f18.jpg', 'baza/fizyka/2/fo18.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f19.jpg', 'baza/fizyka/2/fo19.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f20.jpg', 'baza/fizyka/2/fo20.jpg', 0, '', ''),

-- (default, 'fizyka', 2, 'baza/fizyka/2/f21.jpg', 'baza/fizyka/2/fo21.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f22.jpg', 'baza/fizyka/2/fo22.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f23.jpg', 'baza/fizyka/2/fo23.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f24.jpg', 'baza/fizyka/2/fo24.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f25.jpg', 'baza/fizyka/2/fo25.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f26.jpg', 'baza/fizyka/2/fo26.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f27.jpg', 'baza/fizyka/2/fo27.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f28.jpg', 'baza/fizyka/2/fo28.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f29.jpg', 'baza/fizyka/2/fo29.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f30.jpg', 'baza/fizyka/2/fo30.jpg', 0, '', ''),

-- (default, 'fizyka', 2, 'baza/fizyka/2/f31.jpg', 'baza/fizyka/2/fo31.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f32.jpg', 'baza/fizyka/2/fo32.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f33.jpg', 'baza/fizyka/2/fo33.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f34.jpg', 'baza/fizyka/2/fo34.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f35.jpg', 'baza/fizyka/2/fo35.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f36.jpg', 'baza/fizyka/2/fo36.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f37.jpg', 'baza/fizyka/2/fo37.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f38.jpg', 'baza/fizyka/2/fo38.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f39.jpg', 'baza/fizyka/2/fo39.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f40.jpg', 'baza/fizyka/2/fo40.jpg', 0, '', ''),

-- (default, 'fizyka', 2, 'baza/fizyka/2/f41.jpg', 'baza/fizyka/2/fo41.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f42.jpg', 'baza/fizyka/2/fo42.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f43.jpg', 'baza/fizyka/2/fo43.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f44.jpg', 'baza/fizyka/2/fo44.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f45.jpg', 'baza/fizyka/2/fo45.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f46.jpg', 'baza/fizyka/2/fo46.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f47.jpg', 'baza/fizyka/2/fo47.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f48.jpg', 'baza/fizyka/2/fo48.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f49.jpg', 'baza/fizyka/2/fo49.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f50.jpg', 'baza/fizyka/2/fo50.jpg', 0, '', ''),

-- (default, 'fizyka', 2, 'baza/fizyka/2/f51.jpg', 'baza/fizyka/2/fo51.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f52.jpg', 'baza/fizyka/2/fo52.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f53.jpg', 'baza/fizyka/2/fo53.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f54.jpg', 'baza/fizyka/2/fo54.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f55.jpg', 'baza/fizyka/2/fo55.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f56.jpg', 'baza/fizyka/2/fo56.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f57.jpg', 'baza/fizyka/2/fo57.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f58.jpg', 'baza/fizyka/2/fo58.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f59.jpg', 'baza/fizyka/2/fo59.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f60.jpg', 'baza/fizyka/2/fo60.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f61.jpg', 'baza/fizyka/2/fo61.jpg', 0, '', ''),
-- (default, 'fizyka', 2, 'baza/fizyka/2/f62.jpg', 'baza/fizyka/2/fo62.jpg', 0, '', ''),


-- (default, 'informatyka', 1, 'baza/informatyka/1/i1.jpg', 'baza/informatyka/1/io1.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i10.jpg', 'baza/informatyka/1/io10.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i11.jpg', 'baza/informatyka/1/io11.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i12.jpg', 'baza/informatyka/1/io12.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i13.jpg', 'baza/informatyka/1/io13.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i14.jpg', 'baza/informatyka/1/io14.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i15.jpg', 'baza/informatyka/1/io15.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i16.jpg', 'baza/informatyka/1/io16.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i17.jpg', 'baza/informatyka/1/io17.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i18.jpg', 'baza/informatyka/1/io18.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i19.jpg', 'baza/informatyka/1/io19.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i2.jpg', 'baza/informatyka/1/io2.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i20.jpg', 'baza/informatyka/1/io20.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i21.jpg', 'baza/informatyka/1/io21.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i22.jpg', 'baza/informatyka/1/io22.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i23.jpg', 'baza/informatyka/1/io23.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i24.jpg', 'baza/informatyka/1/io24.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i25.jpg', 'baza/informatyka/1/io25.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i26.jpg', 'baza/informatyka/1/io26.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i27.jpg', 'baza/informatyka/1/io27.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i28.jpg', 'baza/informatyka/1/io28.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i29.jpg', 'baza/informatyka/1/io29.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i3.jpg', 'baza/informatyka/1/io3.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i30.jpg', 'baza/informatyka/1/io30.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i31.jpg', 'baza/informatyka/1/io31.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i32.jpg', 'baza/informatyka/1/io32.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i33.jpg', 'baza/informatyka/1/io33.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i34.jpg', 'baza/informatyka/1/io34.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i35.jpg', 'baza/informatyka/1/io35.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i36.jpg', 'baza/informatyka/1/io36.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i37.jpg', 'baza/informatyka/1/io37.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i38.jpg', 'baza/informatyka/1/io38.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i39.jpg', 'baza/informatyka/1/io39.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i4.jpg', 'baza/informatyka/1/io4.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i40.jpg', 'baza/informatyka/1/io40.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i41.jpg', 'baza/informatyka/1/io41.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i42.jpg', 'baza/informatyka/1/io42.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i43.jpg', 'baza/informatyka/1/io43.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i44.jpg', 'baza/informatyka/1/io44.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i45.jpg', 'baza/informatyka/1/io45.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i46.jpg', 'baza/informatyka/1/io46.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i47.jpg', 'baza/informatyka/1/io47.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i5.jpg', 'baza/informatyka/1/io5.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i6.jpg', 'baza/informatyka/1/io6.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i7.jpg', 'baza/informatyka/1/io7.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i8.jpg', 'baza/informatyka/1/io8.jpg', 0, '', ''),
-- (default, 'informatyka', 1, 'baza/informatyka/1/i9.jpg', 'baza/informatyka/1/io9.jpg', 0, '', ''),

-- (default, 'informatyka', 2, 'baza/informatyka/2/id1.jpg', 'baza/informatyka/2/ido1.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id10.jpg', 'baza/informatyka/2/ido10.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id11.jpg', 'baza/informatyka/2/ido11.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id12.jpg', 'baza/informatyka/2/ido12.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id13.jpg', 'baza/informatyka/2/ido13.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id14.jpg', 'baza/informatyka/2/ido14.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id15.jpg', 'baza/informatyka/2/ido15.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id16.jpg', 'baza/informatyka/2/ido16.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id17.jpg', 'baza/informatyka/2/ido17.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id18.jpg', 'baza/informatyka/2/ido18.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id19.jpg', 'baza/informatyka/2/ido19.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id2.jpg', 'baza/informatyka/2/ido2.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id20.jpg', 'baza/informatyka/2/ido20.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id21.jpg', 'baza/informatyka/2/ido21.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id22.jpg', 'baza/informatyka/2/ido22.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id23.jpg', 'baza/informatyka/2/ido23.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id24.jpg', 'baza/informatyka/2/ido24.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id25.jpg', 'baza/informatyka/2/ido25.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id26.jpg', 'baza/informatyka/2/ido26.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id27.jpg', 'baza/informatyka/2/ido27.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id28.jpg', 'baza/informatyka/2/ido28.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id29.jpg', 'baza/informatyka/2/ido29.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id3.jpg', 'baza/informatyka/2/ido3.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id30.jpg', 'baza/informatyka/2/ido30.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id31.jpg', 'baza/informatyka/2/ido31.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id32.jpg', 'baza/informatyka/2/ido32.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id33.jpg', 'baza/informatyka/2/ido33.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id34.jpg', 'baza/informatyka/2/ido34.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id35.jpg', 'baza/informatyka/2/ido35.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id36.jpg', 'baza/informatyka/2/ido36.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id37.jpg', 'baza/informatyka/2/ido37.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id38.jpg', 'baza/informatyka/2/ido38.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id39.jpg', 'baza/informatyka/2/ido39.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id4.jpg', 'baza/informatyka/2/ido4.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id40.jpg', 'baza/informatyka/2/ido40.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id41.jpg', 'baza/informatyka/2/ido41.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id42.jpg', 'baza/informatyka/2/ido42.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id43.jpg', 'baza/informatyka/2/ido43.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id44.jpg', 'baza/informatyka/2/ido44.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id45.jpg', 'baza/informatyka/2/ido45.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id46.jpg', 'baza/informatyka/2/ido46.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id47.jpg', 'baza/informatyka/2/ido47.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id48.jpg', 'baza/informatyka/2/ido48.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id49.jpg', 'baza/informatyka/2/ido49.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id5.jpg', 'baza/informatyka/2/ido5.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id50.jpg', 'baza/informatyka/2/ido50.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id51.jpg', 'baza/informatyka/2/ido51.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id52.jpg', 'baza/informatyka/2/ido52.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id53.jpg', 'baza/informatyka/2/ido53.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id6.jpg', 'baza/informatyka/2/ido6.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id7.jpg', 'baza/informatyka/2/ido7.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id8.jpg', 'baza/informatyka/2/ido8.jpg', 0, '', ''),
-- (default, 'informatyka', 2, 'baza/informatyka/2/id9.jpg', 'baza/informatyka/2/ido9.jpg', 0, '', ''),


-- (default, 'matematyka', 1, 'baza/matematyka/1/m1.jpg', 'baza/matematyka/1/mo1.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m10.jpg', 'baza/matematyka/1/mo10.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m11.jpg', 'baza/matematyka/1/mo11.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m12.jpg', 'baza/matematyka/1/mo12.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m13.jpg', 'baza/matematyka/1/mo13.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m14.jpg', 'baza/matematyka/1/mo14.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m15.jpg', 'baza/matematyka/1/mo15.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m16.jpg', 'baza/matematyka/1/mo16.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m17.jpg', 'baza/matematyka/1/mo17.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m18.jpg', 'baza/matematyka/1/mo18.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m19.jpg', 'baza/matematyka/1/mo19.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m2.jpg', 'baza/matematyka/1/mo2.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m20.jpg', 'baza/matematyka/1/mo20.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m21.jpg', 'baza/matematyka/1/mo21.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m22.jpg', 'baza/matematyka/1/mo22.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m23.jpg', 'baza/matematyka/1/mo23.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m24.jpg', 'baza/matematyka/1/mo24.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m25.jpg', 'baza/matematyka/1/mo25.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m26.jpg', 'baza/matematyka/1/mo26.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m27.jpg', 'baza/matematyka/1/mo27.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m28.jpg', 'baza/matematyka/1/mo28.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m29.jpg', 'baza/matematyka/1/mo29.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m3.jpg', 'baza/matematyka/1/mo3.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m30.jpg', 'baza/matematyka/1/mo30.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m31.jpg', 'baza/matematyka/1/mo31.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m32.jpg', 'baza/matematyka/1/mo32.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m33.jpg', 'baza/matematyka/1/mo33.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m34.jpg', 'baza/matematyka/1/mo34.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m35.jpg', 'baza/matematyka/1/mo35.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m36.jpg', 'baza/matematyka/1/mo36.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m37.jpg', 'baza/matematyka/1/mo37.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m38.jpg', 'baza/matematyka/1/mo38.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m39.jpg', 'baza/matematyka/1/mo39.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m4.jpg', 'baza/matematyka/1/mo4.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m40.jpg', 'baza/matematyka/1/mo40.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m41.jpg', 'baza/matematyka/1/mo41.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m42.jpg', 'baza/matematyka/1/mo42.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m43.jpg', 'baza/matematyka/1/mo43.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m44.jpg', 'baza/matematyka/1/mo44.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m45.jpg', 'baza/matematyka/1/mo45.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m46.jpg', 'baza/matematyka/1/mo46.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m47.jpg', 'baza/matematyka/1/mo47.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m48.jpg', 'baza/matematyka/1/mo48.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m49.jpg', 'baza/matematyka/1/mo49.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m5.jpg', 'baza/matematyka/1/mo5.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m50.jpg', 'baza/matematyka/1/mo50.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m51.jpg', 'baza/matematyka/1/mo51.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m52.jpg', 'baza/matematyka/1/mo52.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m53.jpg', 'baza/matematyka/1/mo53.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m54.jpg', 'baza/matematyka/1/mo54.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m8.jpg', 'baza/matematyka/1/mo8.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m9.jpg', 'baza/matematyka/1/mo9.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m6.jpg', 'baza/matematyka/1/mo6.jpg', 0, '', ''),
-- (default, 'matematyka', 1, 'baza/matematyka/1/m7.jpg', 'baza/matematyka/1/mo7.jpg', 0, '', ''),


-- (default, 'matematyka', 2, 'baza/matematyka/2/m1.jpg', 'baza/matematyka/2/mo1.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m2.jpg', 'baza/matematyka/2/mo2.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m3.jpg', 'baza/matematyka/2/mo3.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m4.jpg', 'baza/matematyka/2/mo4.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m5.jpg', 'baza/matematyka/2/mo5.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m6.jpg', 'baza/matematyka/2/mo6.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m7.jpg', 'baza/matematyka/2/mo7.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m8.jpg', 'baza/matematyka/2/mo8.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m9.jpg', 'baza/matematyka/2/mo9.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m10.jpg', 'baza/matematyka/2/mo10.jpg', 0, '', ''),

-- (default, 'matematyka', 2, 'baza/matematyka/2/m11.jpg', 'baza/matematyka/2/mo11.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m12.jpg', 'baza/matematyka/2/mo12.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m13.jpg', 'baza/matematyka/2/mo13.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m14.jpg', 'baza/matematyka/2/mo14.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m15.jpg', 'baza/matematyka/2/mo15.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m16.jpg', 'baza/matematyka/2/mo16.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m17.jpg', 'baza/matematyka/2/mo17.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m18.jpg', 'baza/matematyka/2/mo18.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m19.jpg', 'baza/matematyka/2/mo19.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m20.jpg', 'baza/matematyka/2/mo20.jpg', 0, '', ''),

-- (default, 'matematyka', 2, 'baza/matematyka/2/m21.jpg', 'baza/matematyka/2/mo21.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m22.jpg', 'baza/matematyka/2/mo22.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m23.jpg', 'baza/matematyka/2/mo23.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m24.jpg', 'baza/matematyka/2/mo24.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m25.jpg', 'baza/matematyka/2/mo25.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m26.jpg', 'baza/matematyka/2/mo26.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m27.jpg', 'baza/matematyka/2/mo27.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m28.jpg', 'baza/matematyka/2/mo28.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m29.jpg', 'baza/matematyka/2/mo29.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m30.jpg', 'baza/matematyka/2/mo30.jpg', 0, '', ''),

-- (default, 'matematyka', 2, 'baza/matematyka/2/m31.jpg', 'baza/matematyka/2/mo31.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m32.jpg', 'baza/matematyka/2/mo32.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m33.jpg', 'baza/matematyka/2/mo33.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m34.jpg', 'baza/matematyka/2/mo34.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m35.jpg', 'baza/matematyka/2/mo35.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m36.jpg', 'baza/matematyka/2/mo36.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m37.jpg', 'baza/matematyka/2/mo37.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m38.jpg', 'baza/matematyka/2/mo38.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m39.jpg', 'baza/matematyka/2/mo39.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m40.jpg', 'baza/matematyka/2/mo40.jpg', 0, '', ''),

-- (default, 'matematyka', 2, 'baza/matematyka/2/m41.jpg', 'baza/matematyka/2/mo41.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m42.jpg', 'baza/matematyka/2/mo42.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m43.jpg', 'baza/matematyka/2/mo43.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m44.jpg', 'baza/matematyka/2/mo44.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m45.jpg', 'baza/matematyka/2/mo45.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m46.jpg', 'baza/matematyka/2/mo46.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m47.jpg', 'baza/matematyka/2/mo47.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m48.jpg', 'baza/matematyka/2/mo48.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m49.jpg', 'baza/matematyka/2/mo49.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m50.jpg', 'baza/matematyka/2/mo50.jpg', 0, '', ''),

-- (default, 'matematyka', 2, 'baza/matematyka/2/m51.jpg', 'baza/matematyka/2/mo51.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m52.jpg', 'baza/matematyka/2/mo52.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m53.jpg', 'baza/matematyka/2/mo53.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m54.jpg', 'baza/matematyka/2/mo54.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m55.jpg', 'baza/matematyka/2/mo55.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m56.jpg', 'baza/matematyka/2/mo56.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m57.jpg', 'baza/matematyka/2/mo57.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m58.jpg', 'baza/matematyka/2/mo58.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m59.jpg', 'baza/matematyka/2/mo59.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m60.jpg', 'baza/matematyka/2/mo60.jpg', 0, '', ''),

-- (default, 'matematyka', 2, 'baza/matematyka/2/m61.jpg', 'baza/matematyka/2/mo61.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m62.jpg', 'baza/matematyka/2/mo62.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m63.jpg', 'baza/matematyka/2/mo63.jpg', 0, '', ''),
-- (default, 'matematyka', 2, 'baza/matematyka/2/m64.jpg', 'baza/matematyka/2/mo64.jpg', 0, '', ''),




-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n1.jpg', 'baza/niespodzianka/1/no1.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n10.jpg', 'baza/niespodzianka/1/no10.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n11.jpg', 'baza/niespodzianka/1/no11.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n12.jpg', 'baza/niespodzianka/1/no12.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n13.jpg', 'baza/niespodzianka/1/no13.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n14.jpg', 'baza/niespodzianka/1/no14.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n15.jpg', 'baza/niespodzianka/1/no15.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n16.jpg', 'baza/niespodzianka/1/no16.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n18.jpg', 'baza/niespodzianka/1/no18.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n19.jpg', 'baza/niespodzianka/1/no19.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n2.jpg', 'baza/niespodzianka/1/no2.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n20.jpg', 'baza/niespodzianka/1/no20.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n21.jpg', 'baza/niespodzianka/1/no21.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n22.jpg', 'baza/niespodzianka/1/no22.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n23.jpg', 'baza/niespodzianka/1/no23.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n24.jpg', 'baza/niespodzianka/1/no24.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n25.jpg', 'baza/niespodzianka/1/no25.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n26.jpg', 'baza/niespodzianka/1/no26.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n27.jpg', 'baza/niespodzianka/1/no27.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n28.jpg', 'baza/niespodzianka/1/no28.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n29.jpg', 'baza/niespodzianka/1/no29.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n3.jpg', 'baza/niespodzianka/1/no3.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n30.jpg', 'baza/niespodzianka/1/no30.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n31.jpg', 'baza/niespodzianka/1/no31.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n32.jpg', 'baza/niespodzianka/1/no32.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n33.jpg', 'baza/niespodzianka/1/no33.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n34.jpg', 'baza/niespodzianka/1/no34.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n35.jpg', 'baza/niespodzianka/1/no35.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n36.jpg', 'baza/niespodzianka/1/no36.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n37.jpg', 'baza/niespodzianka/1/no37.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n38.jpg', 'baza/niespodzianka/1/no38.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n39.jpg', 'baza/niespodzianka/1/no39.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n4.jpg', 'baza/niespodzianka/1/no4.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n40.jpg', 'baza/niespodzianka/1/no40.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n41.jpg', 'baza/niespodzianka/1/no41.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n42.jpg', 'baza/niespodzianka/1/no42.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n43.jpg', 'baza/niespodzianka/1/no43.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n44.jpg', 'baza/niespodzianka/1/no44.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n45.jpg', 'baza/niespodzianka/1/no45.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n46.jpg', 'baza/niespodzianka/1/no46.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n47.jpg', 'baza/niespodzianka/1/no47.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n48.jpg', 'baza/niespodzianka/1/no48.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n49.jpg', 'baza/niespodzianka/1/no49.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n5.jpg', 'baza/niespodzianka/1/no5.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n50.jpg', 'baza/niespodzianka/1/no50.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n51.jpg', 'baza/niespodzianka/1/no51.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n52.jpg', 'baza/niespodzianka/1/no52.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n53.jpg', 'baza/niespodzianka/1/no53.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n54.jpg', 'baza/niespodzianka/1/no54.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n55.jpg', 'baza/niespodzianka/1/no55.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n56.jpg', 'baza/niespodzianka/1/no56.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n6.jpg', 'baza/niespodzianka/1/no6.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n7.jpg', 'baza/niespodzianka/1/no7.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n8.jpg', 'baza/niespodzianka/1/no8.jpg', 0, '', ''),
-- (default, 'niespodzianka', 1, 'baza/niespodzianka/1/n9.jpg', 'baza/niespodzianka/1/no9.jpg', 0, '', ''),


-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n1.jpg', 'baza/niespodzianka/2/no1.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n2.jpg', 'baza/niespodzianka/2/no2.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n3.jpg', 'baza/niespodzianka/2/no3.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n4.jpg', 'baza/niespodzianka/2/no4.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n5.jpg', 'baza/niespodzianka/2/no5.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n6.jpg', 'baza/niespodzianka/2/no6.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n7.jpg', 'baza/niespodzianka/2/no7.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n8.jpg', 'baza/niespodzianka/2/no8.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n9.jpg', 'baza/niespodzianka/2/no9.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n10.jpg', 'baza/niespodzianka/2/no10.jpg', 0, '', ''),

-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n11.jpg', 'baza/niespodzianka/2/no11.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n12.jpg', 'baza/niespodzianka/2/no12.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n13.jpg', 'baza/niespodzianka/2/no13.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n14.jpg', 'baza/niespodzianka/2/no14.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n15.jpg', 'baza/niespodzianka/2/no15.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n16.jpg', 'baza/niespodzianka/2/no16.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n17.jpg', 'baza/niespodzianka/2/no17.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n18.jpg', 'baza/niespodzianka/2/no18.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n19.jpg', 'baza/niespodzianka/2/no19.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n20.jpg', 'baza/niespodzianka/2/no20.jpg', 0, '', ''),

-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n21.jpg', 'baza/niespodzianka/2/no21.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n22.jpg', 'baza/niespodzianka/2/no22.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n23.jpg', 'baza/niespodzianka/2/no23.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n24.jpg', 'baza/niespodzianka/2/no24.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n25.jpg', 'baza/niespodzianka/2/no25.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n26.jpg', 'baza/niespodzianka/2/no26.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n27.jpg', 'baza/niespodzianka/2/no27.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n28.jpg', 'baza/niespodzianka/2/no28.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n29.jpg', 'baza/niespodzianka/2/no29.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n30.jpg', 'baza/niespodzianka/2/no30.jpg', 0, '', ''),

-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n31.jpg', 'baza/niespodzianka/2/no31.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n32.jpg', 'baza/niespodzianka/2/no32.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n33.jpg', 'baza/niespodzianka/2/no33.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n34.jpg', 'baza/niespodzianka/2/no34.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n35.jpg', 'baza/niespodzianka/2/no35.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n36.jpg', 'baza/niespodzianka/2/no36.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n37.jpg', 'baza/niespodzianka/2/no37.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n38.jpg', 'baza/niespodzianka/2/no38.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n39.jpg', 'baza/niespodzianka/2/no39.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n40.jpg', 'baza/niespodzianka/2/no40.jpg', 0, '', ''),

-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n41.jpg', 'baza/niespodzianka/2/no41.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n42.jpg', 'baza/niespodzianka/2/no42.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n43.jpg', 'baza/niespodzianka/2/no43.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n44.jpg', 'baza/niespodzianka/2/no44.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n45.jpg', 'baza/niespodzianka/2/no45.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n46.jpg', 'baza/niespodzianka/2/no46.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n47.jpg', 'baza/niespodzianka/2/no47.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n48.jpg', 'baza/niespodzianka/2/no48.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n49.jpg', 'baza/niespodzianka/2/no49.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n50.jpg', 'baza/niespodzianka/2/no50.jpg', 0, '', ''),

-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n51.jpg', 'baza/niespodzianka/2/no51.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n52.jpg', 'baza/niespodzianka/2/no52.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n53.jpg', 'baza/niespodzianka/2/no53.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n54.jpg', 'baza/niespodzianka/2/no54.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n55.jpg', 'baza/niespodzianka/2/no55.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n56.jpg', 'baza/niespodzianka/2/no56.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n57.jpg', 'baza/niespodzianka/2/no57.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n58.jpg', 'baza/niespodzianka/2/no58.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n59.jpg', 'baza/niespodzianka/2/no59.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n60.jpg', 'baza/niespodzianka/2/no60.jpg', 0, '', ''),

-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n61.jpg', 'baza/niespodzianka/2/no61.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n62.jpg', 'baza/niespodzianka/2/no62.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n63.jpg', 'baza/niespodzianka/2/no63.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n64.jpg', 'baza/niespodzianka/2/no64.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n65.jpg', 'baza/niespodzianka/2/no65.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n66.jpg', 'baza/niespodzianka/2/no66.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n67.jpg', 'baza/niespodzianka/2/no67.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n68.jpg', 'baza/niespodzianka/2/no68.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n69.jpg', 'baza/niespodzianka/2/no69.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n70.jpg', 'baza/niespodzianka/2/no70.jpg', 0, '', ''),

-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n71.jpg', 'baza/niespodzianka/2/no71.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n72.jpg', 'baza/niespodzianka/2/no72.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n73.jpg', 'baza/niespodzianka/2/no73.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n74.jpg', 'baza/niespodzianka/2/no74.jpg', 0, '', ''),
-- (default, 'niespodzianka', 2, 'baza/niespodzianka/2/n75.jpg', 'baza/niespodzianka/2/no75.jpg', 0, '', ''),

-- (default, 'technika', 1, 'baza/technika/1/t1.jpg', 'baza/technika/1/to1.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t10.jpg', 'baza/technika/1/to10.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t11.jpg', 'baza/technika/1/to11.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t12.jpg', 'baza/technika/1/to12.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t13.jpg', 'baza/technika/1/to13.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t14.jpg', 'baza/technika/1/to14.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t15.jpg', 'baza/technika/1/to15.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t16.jpg', 'baza/technika/1/to16.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t17.jpg', 'baza/technika/1/to17.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t18.jpg', 'baza/technika/1/to18.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t19.jpg', 'baza/technika/1/to19.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t2.jpg', 'baza/technika/1/to2.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t20.jpg', 'baza/technika/1/to20.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t21.jpg', 'baza/technika/1/to21.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t22.jpg', 'baza/technika/1/to22.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t23.jpg', 'baza/technika/1/to23.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t24.jpg', 'baza/technika/1/to24.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t25.jpg', 'baza/technika/1/to25.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t26.jpg', 'baza/technika/1/to26.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t27.jpg', 'baza/technika/1/to27.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t28.jpg', 'baza/technika/1/to28.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t29.jpg', 'baza/technika/1/to29.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t3.jpg', 'baza/technika/1/to3.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t30.jpg', 'baza/technika/1/to30.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t31.jpg', 'baza/technika/1/to31.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t32.jpg', 'baza/technika/1/to32.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t33.jpg', 'baza/technika/1/to33.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t34.jpg', 'baza/technika/1/to34.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t35.jpg', 'baza/technika/1/to35.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t36.jpg', 'baza/technika/1/to36.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t37.jpg', 'baza/technika/1/to37.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t38.jpg', 'baza/technika/1/to38.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t39.jpg', 'baza/technika/1/to39.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t4.jpg', 'baza/technika/1/to4.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t40.jpg', 'baza/technika/1/to40.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t41.jpg', 'baza/technika/1/to41.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t42.jpg', 'baza/technika/1/to42.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t43.jpg', 'baza/technika/1/to43.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t44.jpg', 'baza/technika/1/to44.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t45.jpg', 'baza/technika/1/to45.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t46.jpg', 'baza/technika/1/to46.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t47.jpg', 'baza/technika/1/to47.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t48.jpg', 'baza/technika/1/to48.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t49.jpg', 'baza/technika/1/to49.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t5.jpg', 'baza/technika/1/to5.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t50.jpg', 'baza/technika/1/to50.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t51.jpg', 'baza/technika/1/to51.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t52.jpg', 'baza/technika/1/to52.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t53.jpg', 'baza/technika/1/to53.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t54.jpg', 'baza/technika/1/to54.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t55.jpg', 'baza/technika/1/to55.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t56.jpg', 'baza/technika/1/to56.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t57.jpg', 'baza/technika/1/to57.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t58.jpg', 'baza/technika/1/to58.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t59.jpg', 'baza/technika/1/to59.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t6.jpg', 'baza/technika/1/to6.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t60.jpg', 'baza/technika/1/to60.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t61.jpg', 'baza/technika/1/to61.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t62.jpg', 'baza/technika/1/to62.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t63.jpg', 'baza/technika/1/to63.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t64.jpg', 'baza/technika/1/to64.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t65.jpg', 'baza/technika/1/to65.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t66.jpg', 'baza/technika/1/to66.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t67.jpg', 'baza/technika/1/to67.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t68.jpg', 'baza/technika/1/to68.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t7.jpg', 'baza/technika/1/to7.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t8.jpg', 'baza/technika/1/to8.jpg', 0, '', ''),
-- (default, 'technika', 1, 'baza/technika/1/t9.jpg', 'baza/technika/1/to9.jpg', 0, '', ''),

-- (default, 'technika', 2, 'baza/technika/2/t1.jpg', 'baza/technika/2/to1.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t2.jpg', 'baza/technika/2/to2.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t3.jpg', 'baza/technika/2/to3.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t4.jpg', 'baza/technika/2/to4.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t5.jpg', 'baza/technika/2/to5.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t6.jpg', 'baza/technika/2/to6.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t7.jpg', 'baza/technika/2/to7.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t8.jpg', 'baza/technika/2/to8.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t9.jpg', 'baza/technika/2/to9.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t10.jpg', 'baza/technika/2/to10.jpg', 0, '', ''),

-- (default, 'technika', 2, 'baza/technika/2/t11.jpg', 'baza/technika/2/to11.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t12.jpg', 'baza/technika/2/to12.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t13.jpg', 'baza/technika/2/to13.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t14.jpg', 'baza/technika/2/to14.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t15.jpg', 'baza/technika/2/to15.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t16.jpg', 'baza/technika/2/to16.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t17.jpg', 'baza/technika/2/to17.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t18.jpg', 'baza/technika/2/to18.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t19.jpg', 'baza/technika/2/to19.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t20.jpg', 'baza/technika/2/to20.jpg', 0, '', ''),

-- (default, 'technika', 2, 'baza/technika/2/t21.jpg', 'baza/technika/2/to21.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t22.jpg', 'baza/technika/2/to22.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t23.jpg', 'baza/technika/2/to23.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t24.jpg', 'baza/technika/2/to24.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t25.jpg', 'baza/technika/2/to25.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t26.jpg', 'baza/technika/2/to26.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t27.jpg', 'baza/technika/2/to27.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t28.jpg', 'baza/technika/2/to28.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t29.jpg', 'baza/technika/2/to29.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t30.jpg', 'baza/technika/2/to30.jpg', 0, '', ''),

-- (default, 'technika', 2, 'baza/technika/2/t31.jpg', 'baza/technika/2/to31.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t32.jpg', 'baza/technika/2/to32.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t33.jpg', 'baza/technika/2/to33.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t34.jpg', 'baza/technika/2/to34.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t35.jpg', 'baza/technika/2/to35.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t36.jpg', 'baza/technika/2/to36.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t37.jpg', 'baza/technika/2/to37.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t38.jpg', 'baza/technika/2/to38.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t39.jpg', 'baza/technika/2/to39.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t40.jpg', 'baza/technika/2/to40.jpg', 0, '', ''),

-- (default, 'technika', 2, 'baza/technika/2/t41.jpg', 'baza/technika/2/to41.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t42.jpg', 'baza/technika/2/to42.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t43.jpg', 'baza/technika/2/to43.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t44.jpg', 'baza/technika/2/to44.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t45.jpg', 'baza/technika/2/to45.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t46.jpg', 'baza/technika/2/to46.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t47.jpg', 'baza/technika/2/to47.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t48.jpg', 'baza/technika/2/to48.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t49.jpg', 'baza/technika/2/to49.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t50.jpg', 'baza/technika/2/to50.jpg', 0, '', ''),

-- (default, 'technika', 2, 'baza/technika/2/t51.jpg', 'baza/technika/2/to51.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t52.jpg', 'baza/technika/2/to52.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t53.jpg', 'baza/technika/2/to53.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t54.jpg', 'baza/technika/2/to54.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t55.jpg', 'baza/technika/2/to55.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t56.jpg', 'baza/technika/2/to56.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t57.jpg', 'baza/technika/2/to57.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t58.jpg', 'baza/technika/2/to58.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t59.jpg', 'baza/technika/2/to59.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t60.jpg', 'baza/technika/2/to60.jpg', 0, '', ''),

-- (default, 'technika', 2, 'baza/technika/2/t61.jpg', 'baza/technika/2/to61.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t62.jpg', 'baza/technika/2/to62.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t63.jpg', 'baza/technika/2/to63.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t64.jpg', 'baza/technika/2/to64.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t65.jpg', 'baza/technika/2/to65.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t66.jpg', 'baza/technika/2/to66.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t67.jpg', 'baza/technika/2/to67.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t68.jpg', 'baza/technika/2/to68.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t69.jpg', 'baza/technika/2/to69.jpg', 0, '', ''),
-- (default, 'technika', 2, 'baza/technika/2/t70.jpg', 'baza/technika/2/to70.jpg', 0, '', '');

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `mvc_konkurs_wyniki`
--

CREATE TABLE IF NOT EXISTS `mvc_konkurs_wyniki` (
  `id` int(11) NOT NULL PRIMARY KEY,
  `nazwa` varchar(250) NOT NULL,
  `wynik` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------
  